# Generated by Django 4.0.6 on 2022-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='market_capital',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_change_percentage_24h',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
